-- Update allowed_items table with complete Arc Raiders item list (195 items, no missions)
-- Clear existing items first
TRUNCATE TABLE allowed_items;

-- Insert all Arc Raiders items from the CSV
INSERT INTO allowed_items (icon_url, name, rarity, category) VALUES
('https://static.wikia.nocookie.net/arc-raiders/images/3/31/Advanced_ARC_Powercell.png', 'Advanced ARC Powercell', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9b/Advanced_Electrical_Components.png', 'Advanced Electrical Components', 'Rare', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/25/Advanced_Mechanical_Components.png', 'Advanced Mechanical Components', 'Rare', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/4/47/Agave.png', 'Agave', 'Uncommon', 'Nature'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a8/Agave_Juice.png', 'Agave Juice', 'Common', 'Quick Use'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/03/Air_Freshener.png', 'Air Freshener', 'Uncommon', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/95/Alarm_Clock.png', 'Alarm Clock', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/f/f5/Antiseptic.png', 'Antiseptic', 'Rare', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/f/fc/Apricot.png', 'Apricot', 'Uncommon', 'Nature'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a6/ARC_Alloy.png', 'ARC Alloy', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/dc/ARC_Circuitry.png', 'ARC Circuitry', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e9/ARC_Coolant.png', 'ARC Coolant', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/29/ARC_Flex_Rubber.png', 'ARC Flex Rubber', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/ad/ARC_Motion_Core.png', 'ARC Motion Core', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/02/ARC_Performance_Steel.png', 'ARC Performance Steel', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/df/ARC_Powercell.png', 'ARC Powercell', 'Common', 'Misc'),
('https://static.wikia.nocookie.net/arc-raiders/images/7/72/ARC_Synthetic_Resin.png', 'ARC Synthetic Resin', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/0f/ARC_Thermo_Lining.png', 'ARC Thermo Lining', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/51/Assorted_Seeds.png', 'Assorted Seeds', 'Common', 'Nature'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/06/Bastion_Cell.png', 'Bastion Cell', 'Epic', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/6d/Battery.png', 'Battery', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/f/fa/Bicycle_Pump.png', 'Bicycle Pump', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/01/Bloated_Tuna_Can.png', 'Bloated Tuna Can', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/4/46/Bombardier_Cell.png', 'Bombardier Cell', 'Epic', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/63/Breathtaking_Snow_Globe.png', 'Breathtaking Snow Globe', 'Epic', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/17/Broken_Flashlight.png', 'Broken Flashlight', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/93/Broken_Guidance_System.png', 'Broken Guidance System', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/3b/Broken_Handheld_Radio.png', 'Broken Handheld Radio', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/18/Broken_Taser.png', 'Broken Taser', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a5/Burned_ARC_Circuity.png', 'Burned ARC Circuitry', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a6/Camera_Lens.png', 'Camera Lens', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/58/Candle_Holder.png', 'Candle Holder', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/5f/Canister.png', 'Canister', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/82/Cat_Bed.png', 'Cat Bed', 'Uncommon', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/92/Chemicals.png', 'Chemicals', 'Common', 'Basic Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/33/Coffee_Pot.png', 'Coffee Pot', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/3d/Complex_Gun_Parts.png', 'Complex Gun Parts', 'Epic', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/4/40/Coolant.png', 'Coolant', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/7/7f/Cooling_Coil.png', 'Cooling Coil', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/13/Cooling_Fan.png', 'Cooling Fan', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9a/Cracked_Bioscanner.png', 'Cracked Bioscanner', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/f/fc/Crude_Explosives.png', 'Crude Explosives', 'Uncommon', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/8e/Crumpled_Plastic_Bottle.png', 'Crumpled Plastic Bottle', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9e/Damaged_ARC_Motion_Core.png', 'Damaged ARC Motion Core', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/58/Damaged_ARC_Powercell.png', 'Damaged ARC Powercell', 'Common', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/d8/Damaged_Fireball_Burner.png', 'Damaged Fireball Burner', 'Common', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/1f/Damaged_Heat_Sink.png', 'Damaged Heat Sink', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/96/Damaged_Hornet_Driver.png', 'Damaged Hornet Driver', 'Common', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/3a/Damaged_Rocketeer_Driver.png', 'Damaged Rocketeer Driver', 'Common', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/d6/Damaged_Tick_Pod.png', 'Damaged Tick Pod', 'Common', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e6/Damaged_Wasp_Driver.png', 'Damaged Wasp Driver', 'Common', 'Recyclable');

-- Continue with remaining items (part 2 of 4)
INSERT INTO allowed_items (icon_url, name, rarity, category) VALUES
('https://static.wikia.nocookie.net/arc-raiders/images/4/4d/Dart_Board.png', 'Dart Board', 'Uncommon', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/7/7c/Deflated_Football.png', 'Deflated Football', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/37/Degraded_ARC_Rubber.png', 'Degraded ARC Rubber', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/1a/Diving_Goggles.png', 'Diving Goggles', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c5/Dog_Collar.png', 'Dog Collar', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/d0/Dried_Out_ARC_Resin.png', 'Dried-Out ARC Resin', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/4/4e/Duct_Tape.png', 'Duct Tape', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/25/Durable_Cloth.png', 'Durable Cloth', 'Uncommon', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/06/Electrical_Components.png', 'Electrical Components', 'Uncommon', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e1/Empty_Wine_Bottle.png', 'Empty Wine Bottle', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/1b/Exodus_Modules.png', 'Exodus Modules', 'Epic', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/91/Expired_Pasta.png', 'Expired Pasta', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/b/ba/Expired_Respirator.png', 'Expired Respirator', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/11/Explosive_Compound.png', 'Explosive Compound', 'Rare', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/2b/Fabric.png', 'Fabric', 'Common', 'Basic Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/0c/Faded_Photograph.png', 'Faded Photograph', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/25/Fertilizer.png', 'Fertilizer', 'Uncommon', 'Nature'),
('https://static.wikia.nocookie.net/arc-raiders/images/4/44/Film_Reel.png', 'Film Reel', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/94/Fine_Wristwatch.png', 'Fine Wristwatch', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/8b/Fireball_Burner.png', 'Fireball Burner', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/b/b6/Flow_Controller.png', 'Flow Controller', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/36/Frequency_Modulation_Box.png', 'Frequency Modulation Box', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/29/Fried_Motherboard.png', 'Fried Motherboard', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/81/FryingPanPNG.png', 'Frying Pan', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/88/Garlic_Press.png', 'Garlic Press', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/37/Geiger_Counter.png', 'Geiger Counter', 'Epic', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/0d/Great_Mullein.png', 'Great Mullein', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/0f/Headphones.png', 'Headphones', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/33/Heavy_Gun_Parts.png', 'Heavy Gun Parts', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/b/bb/Hornet_Driver.png', 'Hornet Driver', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e8/HouseholdCleanerPNG.png', 'Household Cleaner', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/4/4b/Humidifier.png', 'Humidifier', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c9/Ice_Cream_Scooper.png', 'Ice Cream Scooper', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a0/Impure_ARC_Coolant.png', 'Impure ARC Coolant', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c9/Industrial_Battery.png', 'Industrial Battery', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/66/Industrial_Charger.png', 'Industrial Charger', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/38/Industrial_Magnet.png', 'Industrial Magnet', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e7/Ion_Sputter.png', 'Ion Sputter', 'Epic', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e5/Laboratory_Reagents.png', 'Laboratory Reagents', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/ef/Lances_Mixtape.png', 'Lance''s Mixtape (5th Edition)', 'Epic', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a0/Leaper_Pulse_Unit.png', 'Leaper Pulse Unit', 'Epic', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/35/Lemon.png', 'Lemon', 'Uncommon', 'Nature'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c9/Light_Gun_Parts.png', 'Light Gun Parts', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/2c/Light_Bulb.png', 'Light Bulb', 'Uncommon', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/8c/Magnet.png', 'Magnet', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/5e/Magnetic_Accelerator.png', 'Magnetic Accelerator', 'Epic', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a2/Magnetron.png', 'Magnetron', 'Epic', 'Recycleable'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/24/Matriarch_Reactor.png', 'Matriarch Reactor', 'Legendary', 'Recycleable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/94/Mechanical_Components.png', 'Mechanical Components', 'Uncommon', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9a/Medium_Gun_Parts.png', 'Medium Gun Parts', 'Rare', 'Topside Material');

-- Part 3 of 4
INSERT INTO allowed_items (icon_url, name, rarity, category) VALUES
('https://static.wikia.nocookie.net/arc-raiders/images/6/62/Metal_Brackets.png', 'Metal Brackets', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/89/Metal_Parts.png', 'Metal Parts', 'Common', 'Basic Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/2c/Microscope.png', 'Microscope', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9f/Mini_Centrifuge.png', 'Mini Centrifuge', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/0f/Mod_Components.png', 'Mod Components', 'Rare', 'Refined Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/64/Moss.png', 'Moss', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/0f/Motor.png', 'Motor', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/8c/Mushroom.png', 'Mushroom', 'Common', 'Misc'),
('https://static.wikia.nocookie.net/arc-raiders/images/7/74/Music_Box.png', 'Music Box', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/90/Music_Album.png', 'Music Album', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/51/Number_Plate.png', 'Number Plate', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/06/Oil.png', 'Oil', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/f/f3/Olives.png', 'Olives', 'Uncommon', 'Nature'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/53/Painted_Box.png', 'Painted Box', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c9/Plastic_Parts.png', 'Plastic Parts', 'Common', 'Basic Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e2/Playing_Cards.png', 'Playing Cards', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c0/Pottery.png', 'Pottery', 'Uncommon', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/6e/Polluted_Air_Filter.png', 'Polluted Air Filter', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c6/Pop_Trigger.png', 'Pop Trigger', 'Common', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/5f/Portable_TV.png', 'Portable TV', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/2b/Poster_Of_Natural_Wonders.png', 'Poster of Natural Wonders', 'Uncommon', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/7/77/Power_Bank.png', 'Power Bank', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/f/f8/Power_Cable.png', 'Power Cable', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/b/b7/PowerRod.png', 'Power Rod', 'Epic', 'Advanced Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/80/Prickly_Pear.png', 'Prickly Pear', 'Uncommon', 'Misc'),
('https://static.wikia.nocookie.net/arc-raiders/images/4/4e/Processor.png', 'Processor', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/04/Projector.png', 'Projector', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/6b/Queen_Reactor.png', 'Queen Reactor', 'Legendary', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/31/Radio.png', 'Radio', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/b/b6/Radio_Relay.png', 'Radio Relay', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/2c/Resin.png', 'Resin', 'Common', 'Nature'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/6d/Recorder.png', 'Recorder', 'Uncommon', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/1a/Red_Coral_Jewelry.png', 'Red Coral Jewelry', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/f/f4/Remote_Control.png', 'Remote Control', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a8/Ripped_Safety_Vest.png', 'Ripped Safety Vest', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/53/Rocketeet_Driver.png', 'Rocketeer Driver', 'Epic', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/8a/Rocket_Thruster.png', 'Rocket Thruster', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/57/Roots.png', 'Roots', 'Uncommon', 'Nature'),
('https://static.wikia.nocookie.net/arc-raiders/images/b/b4/Rope.png', 'Rope', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/7/77/Rosary.png', 'Rosary', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e4/Rotary_Encoder.png', 'Rotary Encoder', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/df/Rubber_Duck.png', 'Rubber Duck', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/1a/Rubber_Pad.png', 'Rubber Pad', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/93/Rubber_Parts.png', 'Rubber Parts', 'Common', 'Basic Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9b/Ruined_Accordon.png', 'Ruined Accordion', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/ee/Ruined_Baton.png', 'Ruined Baton', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/7/7c/Ruined_Handcuffs.png', 'Ruined Handcuffs', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/5c/Ruined_Parachute.png', 'Ruined Parachute', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/cb/Ruined_Riot_Shield.png', 'Ruined Riot Shield', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c2/Ruined_Tactical_Vest.png', 'Ruined Tactical Vest', 'Uncommon', 'Recyclable');

-- Part 4 of 4
INSERT INTO allowed_items (icon_url, name, rarity, category) VALUES
('https://static.wikia.nocookie.net/arc-raiders/images/b/bf/Rusted_Bolts.png', 'Rusted Bolts', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/cf/Rusted_Gear.png', 'Rusted Gear', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/1a/Rusted_Shut_Medical_Kit.png', 'Rusted Shut Medical Kit', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/30/Rusted_Tools.png', 'Rusted Tools', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/33/Rusty_ARC_Steel.png', 'Rusty ARC Steel', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/d8/Sample_Cleaner.png', 'Sample Cleaner', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9c/Sensors.png', 'Sensors', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/91/Sentinel_Firing_Core.png', 'Sentinel Firing Core', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/b/b1/Shredder_Gryo.png', 'Shredder Gyro', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/de/Signal_Amplifier.png', 'Signal Amplifier', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/90/Silver_Teaspoon_Set.png', 'Silver Teaspoon Set', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/da/Simple_Gun_Parts.png', 'Simple Gun Parts', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/07/SnitchScannerPNG.png', 'Snitch Scanner', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/ee/Speaker_Component.png', 'Speaker Component', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/0e/Spectrometer.png', 'Spectrometer', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/ee/Spectrum_Analyizer.png', 'Spectrum Analyzer', 'Epic', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/58/Spotter_Relay.png', 'Spotter Relay', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/29/SpringCushionPNG.png', 'Spring Cushion', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/8a/Statuette.png', 'Statuette', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/db/Steel_Spring.png', 'Steel Spring', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a9/Surveyor_Vault.png', 'Surveyor Vault', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/8/8e/Synthesized_Fuel.png', 'Synthesized Fuel', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/1/17/Syringe.png', 'Syringe', 'Rare', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/3/35/Tattered_ARC_Lining.png', 'Tattered ARC Lining', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/c4/Tattered_Clothes.png', 'Tattered Clothes', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/a8/Telemetry_Transceiver.png', 'Telemetry Transceiver', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9a/Thermostat.png', 'Thermostat', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/95/Tick_Pod.png', 'Tick Pod', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/5/50/Toaster.png', 'Toaster', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/c/cc/Torn_Book.png', 'Torn Book', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/a/af/Torn_Blanket.png', 'Torn Blanket', 'Common', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9a/Turbine_Cell.png', 'Turbine Cell', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/d/d2/USB_Drive.png', 'USB Drive', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/4/42/Vintage_Calculator.png', 'Vintage Calculator', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/6c/Vintage_Lighter.png', 'Vintage Lighter', 'Rare', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/e/e5/Vintage_Toy.png', 'Vintage Toy', 'Uncommon', 'Trinket'),
('https://static.wikia.nocookie.net/arc-raiders/images/6/68/Walkie_Talkie.png', 'Walkie Talkie', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/0/00/Wasp_Driver.png', 'Wasp Driver', 'Uncommon', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/23/Wireless_Router.png', 'Wireless Router', 'Rare', 'Recyclable'),
('https://static.wikia.nocookie.net/arc-raiders/images/9/9c/Wiring.png', 'Wiring', 'Uncommon', 'Topside Material'),
('https://static.wikia.nocookie.net/arc-raiders/images/2/21/Worn_Wallet.png', 'Worn Wallet', 'Common', 'Trinket');
