-- Add Blueprints category to allowed_items table
-- This script adds all 69 Arc Raiders blueprints

-- Insert all blueprints from the provided list
INSERT INTO allowed_items (name, category, rarity, icon_url) VALUES
('Anvil', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Anvil_Blueprint.png'),
('Angled Grip II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Angled_Grip_II_Blueprint.png'),
('Angled Grip III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Angled_Grip_III_Blueprint.png'),
('Aphelion', 'Blueprint', 'Epic', 'https://arc-raiders.fandom.com/wiki/File:Aphelion_Blueprint.png'),
('Barricade Kit', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Barricade_Kit_Blueprint.png'),
('Bettina', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Bettina_Blueprint.png'),
('Blaze Grenade', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Blaze_Grenade_Blueprint.png'),
('Blue Light Stick', 'Blueprint', 'Common', 'https://arc-raiders.fandom.com/wiki/File:Blue_Light_Stick_Blueprint.png'),
('Bobcat', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Bobcat_Blueprint.png'),
('Burletta', 'Blueprint', 'Epic', 'https://arc-raiders.fandom.com/wiki/File:Burletta_Blueprint.png'),
('Combat MK.3 (Aggresive)', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Combat_MK.3_Blueprint.png'),
('Combat Mk.3 (Flanking)', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Combat_MK.3_Blueprint.png'),
('Compensator II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Compensator_II_Blueprint.png'),
('Compensator III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Compensator_III_Blueprint.png'),
('Complex Gun Parts', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Complex_Gun_Parts_Blueprint.png'),
('Defibrillator', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Defibrillator_Blueprint.png'),
('Explosive Mine', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Explosive_Mine_Blueprint.png'),
('Extended Barrel', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Extended_Barrel_Blueprint.png'),
('Extended Light Magazine II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Extended_Light_Magazine_II_Blueprint.png'),
('Extended Light Magazine III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Extended_Light_Magazine_III_Blueprint.png'),
('Extended Medium Magazine II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Extended_Medium_Magazine_II_Blueprint.png'),
('Extended Medium Mag III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Extended_Medium_Mag_III_Blueprint.png'),
('Extended Shotgun Magazine II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Extended_Shotgun_Magazine_II_Blueprint.png'),
('Extended Shotgun Magazine III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Extended_Shotgun_Magazine_III_Blueprint.png'),
('Equalizer', 'Blueprint', 'Legendary', 'https://arc-raiders.fandom.com/wiki/File:Equalizer_Blueprint.png'),
('Green Light Stick', 'Blueprint', 'Common', 'https://arc-raiders.fandom.com/wiki/File:Green_Light_Stick_Blueprint.png'),
('Heavy Gun Parts', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Heavy_Gun_Parts_Blueprint.png'),
('Horizontal Grip', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Horizontal_Grip_Blueprint.png'),
('Hullcracker', 'Blueprint', 'Legendary', 'https://arc-raiders.fandom.com/wiki/File:Hullcracker_Blueprint.png'),
('IL Toro', 'Blueprint', 'Epic', 'https://arc-raiders.fandom.com/wiki/File:IL_Toro_Blueprint.png'),
('Jolt Mine', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Jolt_Mine_Blueprint.png'),
('Jupiter', 'Blueprint', 'Legendary', 'https://arc-raiders.fandom.com/wiki/File:Jupiter_Blueprint.png'),
('Kinetic Converter', 'Blueprint', 'Epic', 'https://arc-raiders.fandom.com/wiki/File:Kinetic_Converter_Blueprint.png'),
('Light Gun Parts', 'Blueprint', 'Common', 'https://arc-raiders.fandom.com/wiki/File:Light_Gun_Parts_Blueprint.png'),
('Looting MK.3 (Cautious)', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Looting_MK.3_Blueprint.png'),
('Looting MK.3 (Survivor)', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Looting_MK.3_Blueprint.png'),
('Lure Grenade', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Lure_Grenade_Blueprint.png'),
('Medium Gun Parts', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Medium_Gun_Parts_Blueprint.png'),
('Muzzle Brake II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Muzzle_Brake_II_Blueprint.png'),
('Muzzle Brake III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Muzzle_Brake_III_Blueprint.png'),
('Osprey', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Osprey_Blueprint.png'),
('Padded Stock', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Padded_Stock_Blueprint.png'),
('Red Light Stick', 'Blueprint', 'Common', 'https://arc-raiders.fandom.com/wiki/File:Red_Light_Stick_Blueprint.png'),
('Remote Raider Flare', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Remote_Raider_Flare_Blueprint.png'),
('Shotgun Choke II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Shotgun_Choke_II_Blueprint.png'),
('Shotgun Choke III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Shotgun_Choke_III_Blueprint.png'),
('Shotgun Silencer', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Shotgun_Silencer_Blueprint.png'),
('Showstopper', 'Blueprint', 'Epic', 'https://arc-raiders.fandom.com/wiki/File:Showstopper_Blueprint.png'),
('Silencer I', 'Blueprint', 'Common', 'https://arc-raiders.fandom.com/wiki/File:Silencer_I_Blueprint.png'),
('Silencer II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Silencer_II_Blueprint.png'),
('Silencer III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Silencer_III_Blueprint.png'),
('Smoke Grenade', 'Blueprint', 'Common', 'https://arc-raiders.fandom.com/wiki/File:Smoke_Grenade_Blueprint.png'),
('Snap Hook', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Snap_Hook_Blueprint.png'),
('Stable Stock II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Stable_Stock_II_Blueprint.png'),
('Stable Stock III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Stable_Stock_III_Blueprint.png'),
('Tactical MK.3 (Defensive)', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Tactical_MK.3_Blueprint.png'),
('Tactical MK.3 (Healing)', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Tactical_MK.3_Blueprint.png'),
('Tagging Grenade', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Tagging_Grenade_Blueprint.png'),
('Tempest', 'Blueprint', 'Legendary', 'https://arc-raiders.fandom.com/wiki/File:Tempest_Blueprint.png'),
('Torrente', 'Blueprint', 'Epic', 'https://arc-raiders.fandom.com/wiki/File:Torrente_Blueprint.png'),
('Trigger Nade', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Trigger_Nade_Blueprint.png'),
('Venator', 'Blueprint', 'Epic', 'https://arc-raiders.fandom.com/wiki/File:Venator_Blueprint.png'),
('Vertical Grip II', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Vertical_Grip_II_Blueprint.png'),
('Vertical Grip III', 'Blueprint', 'Rare', 'https://arc-raiders.fandom.com/wiki/File:Vertical_Grip_III_Blueprint.png'),
('Vita Shot', 'Blueprint', 'Uncommon', 'https://arc-raiders.fandom.com/wiki/File:Vita_Shot_Blueprint.png'),
('Vita Spray', 'Blueprint', 'Common', 'https://arc-raiders.fandom.com/wiki/File:Vita_Spray_Blueprint.png'),
('Vulcano', 'Blueprint', 'Legendary', 'https://arc-raiders.fandom.com/wiki/File:Vulcano_Blueprint.png'),
('Wolfpack', 'Blueprint', 'Epic', 'https://arc-raiders.fandom.com/wiki/File:Wolfpack_Blueprint.png'),
('Yellow Light Stick', 'Blueprint', 'Common', 'https://arc-raiders.fandom.com/wiki/File:Yellow_Light_Stick_Blueprint.png')
ON CONFLICT (name) DO NOTHING;
